### ISSUE TITLE
What's the relationship between this, the thesis, and the IEEE paper?

### ISSUE THREAD

**Issue by 0joshuaolson1** [sfilip/fquantizer#1]
Are both out of date compared to some parts of the codebase? Does either contain documentation that the other (or this repo) doesn't?

- [Robust tools for weighted Chebyshev approximation and
applications to digital filter design](https://perso.ens-lyon.fr/silviuioan.filip/files/thesis.pdf)
- [Novel robust optimal filter design method and new transition band analysis](https://doi.org/10.1109/BMSB.2013.6621764) (https://ieeexplore.ieee.org/document/6621764/)

**Comment by 0joshuaolson1** [comment]
As far as I can tell, neither cites the other. It would be nice if the repository's description referred to one or something.

**Comment by sfilip** [comment]
Thanks @0joshuaolson1! I've added two relevant references to the readme. I hope you find it clarifying. The first one introduces the prerequisites needed to understand how euclidean lattices are used in the code, but the second one is a more up to date presentation of the method.

fquantizer allows the user to design linear phase FIR filters with coefficients represented using a fixed point format. 

There is no deep connection between the second reference you mention and this code, since the IEEE paper targets FIR filters with floating point coefficients. It is more relevant to talk about it in connection with my firpm repository.

**Comment by 0joshuaolson1** [comment]
> There is no deep connection between the second reference you mention and this code, since the IEEE paper targets FIR filters with floating point coefficients.

Huh? The IEEE paper mentions "float" zero times, and you said it's an update of the first reference, which *is* related to this code?

**Comment by sfilip** [comment]
I'm sorry. It seems my reply caused a misunderstanding. I said the second reference I added to the readme, namely **A lattice basis reduction approach for the design of finite wordlength FIR filters**, is an update to the first one: **Robust tools for weighted Chebyshev approximation and applications to digital filter design**.

The second reference you mention (**Novel Robust Optimal Filter Design Method and
New Transition Band Analysis**) is not directly related to fquantizer. I haven't gone through this paper in detail yet. Indeed, it does not mention "float", but from the text you can tell that it talks about filter design problems with real-valued coefficients (the Eigen-filter and Parks-McClellan methods summarized in Sec. II and the proposed approach in Sec. III assume real-valued coefficients). This means that in practice you would use floating point arithmetic to implement these algorithms. fquantizer, on the other hand, computes filters with integer-valued coefficients (up to a scaling factor). Why would you target integer coefficients? Well, it's related to the fact that FIR filters are often used on devices that do not offer hardware support for floating point arithmetic, only integer/fixed-point arithmetic. I'm happy to provide references regarding this.

**Comment by 0joshuaolson1** [comment]
Wow, I hadn't realized I linked to the wrong paper. My bad, I meant the lattice reduction one...
